server:
  port: 8083

spring:
  application:
    name: 01-Ecommerce-AdminAPI

  # Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/adminapi
    username: root
    password: root

  # ORM properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update